### ISSUE TITLE
how to set msg encoding

### ISSUE THREAD

**Issue by muzico425** [B2W-BIT/aiologger#37]
hello,i want print chinese use,
`logger = JsonLogger.with_default_handlers()`
how to set encoding to "utf-8"

**Comment by diogommartins** [comment]
Hi, @muzico425 !  https://github.com/B2W-BIT/aiologger/blob/ea7909f48011061f1f5571ce1db12d581113b94c/aiologger/handlers.py#L94 is the This is the point where we encode the string into `bytes`. Since an encoding isn't passed, it uses the default [1], which is `utf-8`. Could you provide a code snippet so that i can validate that aiologger fails to output chinese using `with_default_handlers`?

[1] https://docs.python.org/3/library/stdtypes.html#str.encode

**Comment by muzico425** [comment]
like this,when i print .
`import asyncio
from aiologger.loggers.json import JsonLogger


async def log():
    logger = JsonLogger.with_default_handlers()
    return logger


async def start():
    logging = await log()
    await logging.info("什么鬼")
    await logging.shutdown()


if __name__ == '__main__':
    asyncio.run(start())
`

here is result:
```
{"logged_at": "2019-01-21T09:44:51.087198+08:00", "line_number": 17, "function": "start", "level": "INFO", "file_path": "/Users/chennan/Desktop/2019/cosmic_download/aiologtest.py", "msg": "\u4ec0\u4e48\u9b3c"}
```

**Comment by muzico425** [comment]
"msg": "\u4ec0\u4e48\u9b3c"

**Comment by muzico425** [comment]
Thank you。
