### ISSUE TITLE
python3.5

### ISSUE THREAD

**Issue by fried-sausage** [B2W-BIT/aiologger#50]
I use Debian stretch with standard python that goes with it (3.5).
I was able to `pip3 install --user aiologger` despite aiologger being incompatible with python 3.5. Now i see SyntaxError on import.

Also, if author doesn't mind supporting 3.5 i can look into making this package compatible -- for now it seems to me like refactoring variable annotations should be enough.

**Comment by fried-sausage** [comment]
I think in any case we should add python_requires  to setup.py so package won't install on non-supported python versions.

**Comment by diogommartins** [comment]
> I use Debian stretch with standard python that goes with it (3.5).
> I was able to `pip3 install --user aiologger` despite aiologger being incompatible with python 3.5. Now i see SyntaxError on import.
> 
> Also, if author doesn't mind supporting 3.5 i can look into making this package compatible -- for now it seems to me like refactoring variable annotations should be enough.

You're right, the early versions of aiologger used to be compatible with python3.5 as well (although not supported). If you're using aiologger with an unsupported python version, I would recommend that you always fixate the package version, changing your installation into something like: `pip3 install --user aiologger==0.3.0`.

Having python 3.5 support would be nice as we might reach a broader audience for aiologger, but it's something that may not make sense at a long term since new python versions might ship with useful features that would be incompatible with py3.5. If you're willing to help aiologger maintain python3.5 support with that in mind, feel welcome to submit a PR and become a contributor =)

Sorry for the long wait, but it was a busy week and your issue deserved the correct attention and a longer answer.

**Comment by diogommartins** [comment]
> I think in any case we should add python_requires to setup.py so package won't install on non-supported python versions.

You're right. Thanks for the PR !

**Comment by fried-sausage** [comment]
Thank you for the elaborate answer. Not sure when i will be able to look into 3.5 compat, so i guess this can be closed.
