### ISSUE TITLE
logging to stdout/stderr from different thread

### ISSUE THREAD

**Issue by fried-sausage** [B2W-BIT/aiologger#54]
aiologger won't work without event loop instantiated. It also isn't threadsafe. So, do i get it right, the user should instantiate different logger if she wants to log from another thread?

**Comment by diogommartins** [comment]
> aiologger won't work without event loop instantiated. 

That's right. aiologger isn't meant to be used outside a running event loop. It's ok and safe to initialize  aiologger's `Logger` outsite an event loop, but you can't log anything outsite it because you wouldn't be able to run asyncio's Tasks outside it. Every `aiologger.Logger` log functions returns an ` asyncio.Task` instance.

> It also isn't threadsafe. 

That's right. python's `logging.Logger` is threadsafe because of it's general purpose usage nature. aiologger is meant to be used for single threaded asyncio applications. In fact, most of asyncio's objects design isn't threadsafe [1]. 

> So, do i get it right, the user should instantiate different logger if she wants to log from another thread?

I don't know. Could you share a code snippet for me to better understand your use case?

[1]https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading

**Comment by fried-sausage** [comment]
Thanks.

I hope pseudo-code is ok.

My use-case is the following: i use asyncio's `loop.run_in_executor` method to call some blocking functions, and i want to log from those functions.

As of now i just use standard logging.Logger from stdlib.

```
LOG = logging.getLogger(__name__)


async def foo():
    ...
    LOG.info(...)
    loop = get_running_loop()
    await loop.run_in_executor(None, blocking_fun)
    ...


def blocking_fun():
    ...
    LOG.info(...)
    ...

```

I also run some blocking code before running any async code, so i'd also like to have working logger before event loop is started.
```
# main.py
LOG = logging.getLogger(__name__)


async def main():
    ...

if __name__ == "__main__":
    # perform some blocking calls
    ...
    LOG.info(...)
    ...

    asyncio.run(main())
```

**Comment by diogommartins** [comment]
> Thanks.
> 
> I hope pseudo-code is ok.
> 
> My use-case is the following: i use asyncio's `loop.run_in_executor` method to call some blocking functions, and i want to log from those functions.
> 
> As of now i just use standard logging.Logger from stdlib.
> 
> ```
> LOG = logging.getLogger(__name__)
> 
> 
> async def foo():
>     ...
>     LOG.info(...)
>     loop = get_running_loop()
>     await loop.run_in_executor(None, blocking_fun)
>     ...
> 
> 
> def blocking_fun():
>     ...
>     LOG.info(...)
>     ...
> ```
> I also run some blocking code before running any async code, so i'd also like to have working logger before event loop is started.
> 
> ```
> # main.py
> LOG = logging.getLogger(__name__)
> 
> 
> async def main():
>     ...
> 
> if __name__ == "__main__":
>     # perform some blocking calls
>     ...
>     LOG.info(...)
>     ...
> 
>     asyncio.run(main())
> ```

Since aiologger depends on a running event loop, that just wouldn't be possible and you should keep using the stdlib for logging in blocking code delegated to the ThreadPoolExecutor
